import { supabase } from "/js/supabase-client.js";

const $=id=>document.getElementById(id);let user=null,homepage={},settings={},blogPage={},posts=[],editingId=null,dirty=false;
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
const v=id=>($(id)?.value||"").trim();
const setv=(id,val)=>{if($(id))$(id).value=val??""};
const slugify=s=>String(s||"").toLowerCase().trim().replace(/[^a-z0-9\s-]/g,"").replace(/\s+/g,"-").replace(/-+/g,"-");
const msg=(id,text,good=false)=>{const e=$(id);if(e){e.textContent=text;e.style.color=good?"#188653":""}};
const deep=(obj,path,fb="")=>path.split(".").reduce((a,k)=>a?.[k],obj)??fb;

function panel(id){document.querySelectorAll(".panel").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".side").forEach(x=>x.classList.remove("active"));$(id).classList.add("active");document.querySelector(`.side[data-panel="${id}"]`)?.classList.add("active");if(id==="blogPanel")renderPosts();}
function rowDate(p){return p.display_date|| (p.updated_at?new Date(p.updated_at).toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"}):"")}

function renderRepeat(id,items,fields,label){const c=$(id);c.innerHTML="";(items||[]).forEach((x,i)=>{const b=document.createElement("div");b.className="repeat-item";b.innerHTML=`<h4>${label} ${i+1}</h4>`;fields.forEach(f=>{const l=document.createElement("label");l.textContent=f.label;const el=f.type==="textarea"?document.createElement("textarea"):document.createElement("input");if(f.type==="textarea")el.rows=3;el.value=x?.[f.key]||"";el.dataset.i=i;el.dataset.k=f.key;b.appendChild(l);l.appendChild(el)});c.appendChild(b)});}
function readRepeat(id){const items=(()=>{if(id==="trust")return homepage.trust; if(id==="dest")return homepage.destinations?.items; if(id==="benefit")return homepage.betterTogether?.benefits; if(id==="smart")return homepage.smarter?.cards;return []})().map(x=>({...x}));const box=$(id==="trust"?"trustEditor":id==="dest"?"destEditor":id==="benefit"?"benefitEditor":"smartEditor");box.querySelectorAll("[data-i]").forEach(el=>{items[Number(el.dataset.i)][el.dataset.k]=el.value});return items;}

function fillHome(){const s=settings,h=homepage;setv("phone",s.phone);setv("email",s.email);setv("quoteUrl",s.quote_url);setv("homeSeo",s.homepage_seo_title);setv("homeMeta",s.homepage_meta_description);setv("homeOg",s.homepage_og_description);setv("headerHome",deep(h,"header.homeLabel"));setv("headerBlog",deep(h,"header.blogLabel"));setv("headerCall",deep(h,"header.callLabel"));setv("heroEyebrow",deep(h,"hero.eyebrow"));setv("heroTitle",deep(h,"hero.title"));setv("heroHighlight",deep(h,"hero.highlight"));setv("heroDescription",deep(h,"hero.description"));setv("heroMicro",deep(h,"hero.microCopy"));setv("heroImage",deep(h,"hero.imageUrl"));setv("heroAlt",deep(h,"hero.imageAlt"));$("heroPreview").src=deep(h,"hero.imageUrl");renderRepeat("trustEditor",h.trust,[{key:"title",label:"Title"},{key:"text",label:"Text",type:"textarea"}],"Trust item");const d=h.destinations||{};setv("destKicker",d.kicker);setv("destTitle",d.title);setv("destDescription",d.description);setv("destViewAll",d.viewAllLabel);renderRepeat("destEditor",d.items,[{key:"name",label:"Name"},{key:"description",label:"Description",type:"textarea"},{key:"imageUrl",label:"Image URL"},{key:"alt",label:"Image Alt"}],"Destination");const bt=h.betterTogether||{};setv("btKicker",bt.kicker);setv("btTitle",bt.title);setv("btTitle2",bt.title2);setv("btDescription",bt.description);setv("btImage",bt.imageUrl);setv("btAlt",bt.imageAlt);$("btPreview").src=bt.imageUrl||"";renderRepeat("benefitEditor",bt.benefits,[{key:"icon",label:"Icon"},{key:"title",label:"Title"}],"Benefit");const bs=h.blogSection||{};setv("blogKicker",bs.kicker);setv("blogTitle",bs.title);setv("blogDescription",bs.description);setv("blogViewAll",bs.viewAllLabel);const sm=h.smarter||{};setv("smartKicker",sm.kicker);setv("smartTitle",sm.title);setv("smartDescription",sm.description);setv("smartBg",sm.backgroundImageUrl);$("smartPreview").src=sm.backgroundImageUrl||"";renderRepeat("smartEditor",sm.cards,[{key:"num",label:"Number / Step"},{key:"title",label:"Title"},{key:"text",label:"Text",type:"textarea"}],"Travel Smarter card");const c=h.cta||{};setv("ctaKicker",c.kicker);setv("ctaTitle",c.title);setv("ctaDescription",c.description);setv("ctaButton",c.buttonLabel);const f=h.footer||{};setv("footerDescription",f.description);setv("copyright",f.copyright);}
function collectHome(){return {h:{header:{homeLabel:v("headerHome"),blogLabel:v("headerBlog"),callLabel:v("headerCall")},hero:{eyebrow:v("heroEyebrow"),title:v("heroTitle"),highlight:v("heroHighlight"),description:v("heroDescription"),microCopy:v("heroMicro"),imageUrl:v("heroImage"),imageAlt:v("heroAlt")},trust:readRepeat("trust"),destinations:{kicker:v("destKicker"),title:v("destTitle"),description:v("destDescription"),viewAllLabel:v("destViewAll"),items:readRepeat("dest")},betterTogether:{kicker:v("btKicker"),title:v("btTitle"),title2:v("btTitle2"),description:v("btDescription"),imageUrl:v("btImage"),imageAlt:v("btAlt"),benefits:readRepeat("benefit")},blogSection:{kicker:v("blogKicker"),title:v("blogTitle"),description:v("blogDescription"),viewAllLabel:v("blogViewAll")},smarter:{kicker:v("smartKicker"),title:v("smartTitle"),description:v("smartDescription"),backgroundImageUrl:v("smartBg"),cards:readRepeat("smart")},cta:{kicker:v("ctaKicker"),title:v("ctaTitle"),description:v("ctaDescription"),buttonLabel:v("ctaButton")},footer:{description:v("footerDescription"),copyright:v("copyright")}},s:{phone:v("phone"),email:v("email"),quote_url:v("quoteUrl"),homepage_seo_title:v("homeSeo"),homepage_meta_description:v("homeMeta"),homepage_og_description:v("homeOg")}}}
function fillBlogPage(){setv("bpEyebrow",blogPage.eyebrow);setv("bpTitle",blogPage.title);setv("bpDescription",blogPage.description);setv("bpEmpty",blogPage.empty_message);setv("bpSeo",blogPage.seo_title);setv("bpMeta",blogPage.meta_description)}

async function loadSite(){const [{data:s,error:se},{data:h,error:he},{data:b,error:be}]=await Promise.all([supabase.from("site_settings").select("*").eq("id",1).maybeSingle(),supabase.from("homepage_content").select("content").eq("id",1).maybeSingle(),supabase.from("blog_page").select("*").eq("id",1).maybeSingle()]);if(se||he||be)throw se||he||be;settings=s||{};homepage=h?.content||{};blogPage=b||{};fillHome();fillBlogPage();}
async function loadPosts(){const {data,error}=await supabase.from("blog_posts").select("*").order("updated_at",{ascending:false});if(error)throw error;posts=data||[];renderStats();renderPosts();}
function renderStats(){$("statTotal").textContent=posts.length;$('statPublished').textContent=posts.filter(p=>p.published).length;$('statDrafts').textContent=posts.filter(p=>!p.published).length;$('statFeatured').textContent=posts.filter(p=>p.published&&p.featured_on_homepage).length;$("recentPosts").innerHTML=posts.slice(0,6).map(p=>`<div class="row" data-id="${p.id}"><strong>${esc(p.title)}</strong><span>${p.published?'Published':'Draft'} · ${esc(rowDate(p))}</span></div>`).join("")||'<p class="muted">No posts yet.</p>';document.querySelectorAll("#recentPosts .row").forEach(r=>r.onclick=()=>{panel("blogPanel");loadPost(r.dataset.id)});}
function renderPosts(){const q=(v("search")||"").toLowerCase();const f=$("filter").value;const list=posts.filter(p=>(p.title||"").toLowerCase().includes(q)).filter(p=>f==="all"||(f==="published"&&p.published)||(f==="draft"&&!p.published)||(f==="featured"&&p.published&&p.featured_on_homepage));$("postList").innerHTML=list.map(p=>`<div class="row ${editingId===p.id?'active':''}" data-id="${p.id}"><strong>${esc(p.title||'Untitled')}</strong><span>${p.published?'Published':'Draft'}${p.featured_on_homepage?' · Homepage':''} · ${esc(rowDate(p))}</span></div>`).join("")||'<p class="muted">No matching posts.</p>';document.querySelectorAll("#postList .row").forEach(r=>r.onclick=()=>loadPost(r.dataset.id));}
function clearPost(){editingId=null;dirty=false;$("postForm").reset();$("postContent").innerHTML="";$("editorTitle").textContent="New Blog Post";$("badge").textContent="Draft";$("badge").className="badge draft";$("postPreview").src="/assets/blog-default.jpg";updateSEO();msg("postMessage","");renderPosts();}
function loadPost(id){const p=posts.find(x=>x.id===id);if(!p)return;editingId=id;dirty=false;setv("postId",p.id);setv("postTitle",p.title);setv("postSlug",p.slug);setv("postDate",p.display_date);setv("postAuthor",p.author);setv("postSeoTitle",p.seo_title);setv("postKeyphrase",p.focus_keyphrase);setv("postMeta",p.meta_description);setv("postImage",p.featured_image_url);setv("postAlt",p.image_alt);setv("postExcerpt",p.excerpt);$("postContent").innerHTML=p.content_html||"";$("published").checked=!!p.published;$("featured").checked=!!p.featured_on_homepage;$("postPreview").src=p.featured_image_url||"/assets/blog-default.jpg";$("editorTitle").textContent=p.title||"Edit Blog Post";$("badge").textContent=p.published?"Published":"Draft";$("badge").className=`badge ${p.published?'published':'draft'}`;updateSEO();renderPosts();}
function updateSEO(){const slug=slugify(v("postSlug")||v("postTitle")||"your-slug");$("seoTitlePreview").textContent=v("postSeoTitle")||v("postTitle")||"Article Title";$("seoUrlPreview").textContent=`grouptravelairlines.pages.dev/blog/${slug}`;$("seoDescPreview").textContent=v("postMeta")||v("postExcerpt")||"Meta description preview";}
function cleanHtml(){const t=document.createElement("template");t.innerHTML=$("postContent").innerHTML;t.content.querySelectorAll("script,style,iframe,object,embed,form").forEach(e=>e.remove());t.content.querySelectorAll("*").forEach(e=>[...e.attributes].forEach(a=>{if(a.name.toLowerCase().startsWith("on"))e.removeAttribute(a.name)}));return t.innerHTML;}
function collectPost(forcePublished=null){const now=new Date().toISOString();const published=forcePublished===null?$("published").checked:forcePublished;return {title:v("postTitle"),slug:slugify(v("postSlug")||v("postTitle")),display_date:v("postDate"),author:v("postAuthor")||"Group Travel Airlines",seo_title:v("postSeoTitle")||v("postTitle"),focus_keyphrase:v("postKeyphrase"),meta_description:v("postMeta")||v("postExcerpt"),excerpt:v("postExcerpt"),content_html:cleanHtml(),featured_image_url:v("postImage"),image_alt:v("postAlt")||v("postTitle"),published,featured_on_homepage:published&&$("featured").checked,published_at:published?(posts.find(p=>p.id===editingId)?.published_at||now):null,updated_at:now,updated_by:user.id};}
async function savePost(published){const p=collectPost(published);if(!p.title||!p.slug||!p.excerpt){msg("postMessage","Title, slug and excerpt are required.");return;}try{if(editingId){const {error}=await supabase.from("blog_posts").update(p).eq("id",editingId);if(error)throw error;}else{p.created_by=user.id;const {data,error}=await supabase.from("blog_posts").insert(p).select().single();if(error)throw error;editingId=data.id;}dirty=false;msg("postMessage",published?"Article published successfully.":"Draft saved successfully.",true);await loadPosts();loadPost(editingId);}catch(e){msg("postMessage",e.message||"Could not save article.");}}
async function deletePost(){if(!editingId)return;if(!confirm("Delete this article permanently?"))return;const {error}=await supabase.from("blog_posts").delete().eq("id",editingId);if(error){msg("postMessage",error.message);return;}clearPost();await loadPosts();msg("postMessage","Article deleted.",true);}
async function uploadFile(file,target,folder,previewId){if(!file)return;try{msg("postMessage","Uploading image…",true);const ext=(file.name.split(".").pop()||"jpg").toLowerCase();const safe=slugify(file.name.replace(/\.[^.]+$/,""))||"image";const path=`${folder}/${Date.now()}-${safe}.${ext}`;const {error}=await supabase.storage.from("gta-media").upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;const {data}=supabase.storage.from("gta-media").getPublicUrl(path);setv(target,data.publicUrl);if($(previewId))$(previewId).src=data.publicUrl;msg("postMessage","Image uploaded successfully.",true);}catch(e){msg("postMessage",e.message||"Upload failed.");}}

$("loginForm").onsubmit=async e=>{e.preventDefault();try{const {error}=await supabase.auth.signInWithPassword({email:v("loginEmail"),password:v("loginPassword")});if(error)throw error;}catch(err){msg("loginMessage",err.message)}};
$("forgotPassword").onclick=async()=>{try{const {error}=await supabase.auth.resetPasswordForEmail(v("loginEmail"),{redirectTo:location.origin+"/admin"});if(error)throw error;msg("loginMessage","Password reset email sent.",true)}catch(e){msg("loginMessage",e.message)}};
$("logout").onclick=()=>supabase.auth.signOut();document.querySelectorAll(".side").forEach(b=>b.onclick=()=>panel(b.dataset.panel));document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>panel(b.dataset.go));$("dashNewPost").onclick=()=>{panel("blogPanel");clearPost()};$("newPost").onclick=clearPost;$("clearPost").onclick=clearPost;$("refreshAll").onclick=async()=>{try{await loadSite();await loadPosts();msg("dashMessage","Data refreshed.",true)}catch(e){msg("dashMessage",e.message)}};$("previewHome").onclick=()=>window.open("/","_blank");$("search").oninput=renderPosts;$("filter").onchange=renderPosts;
$("homeForm").onsubmit=async e=>{e.preventDefault();const {h,s}=collectHome();try{const a=await supabase.from("homepage_content").update({content:h,updated_at:new Date().toISOString(),updated_by:user.id}).eq("id",1);if(a.error)throw a.error;const b=await supabase.from("site_settings").update({...s,updated_at:new Date().toISOString()}).eq("id",1);if(b.error)throw b.error;homepage=h;settings={...settings,...s};msg("homeMessage","Homepage saved successfully.",true)}catch(err){msg("homeMessage",err.message)}};
$("blogPageForm").onsubmit=async e=>{e.preventDefault();try{const p={eyebrow:v("bpEyebrow"),title:v("bpTitle"),description:v("bpDescription"),empty_message:v("bpEmpty"),seo_title:v("bpSeo"),meta_description:v("bpMeta"),updated_at:new Date().toISOString(),updated_by:user.id};const {error}=await supabase.from("blog_page").update(p).eq("id",1);if(error)throw error;blogPage={...blogPage,...p};msg("bpMessage","Blog page saved successfully.",true)}catch(err){msg("bpMessage",err.message)}};
$("saveDraft").onclick=()=>savePost(false);$("savePublish").onclick=()=>savePost(true);$("deletePost").onclick=deletePost;$("postTitle").oninput=()=>{if(!editingId&&!v("postSlug"))setv("postSlug",slugify(v("postTitle")));updateSEO();dirty=true};["postSlug","postSeoTitle","postMeta","postExcerpt"].forEach(id=>$(id).oninput=()=>{updateSEO();dirty=true});$("postContent").oninput=()=>dirty=true;
$("postUpload").onclick=()=>$("postFile").click();$("postFile").onchange=e=>uploadFile(e.target.files?.[0],"postImage","blog","postPreview");
document.querySelectorAll("[data-upload-for]").forEach(b=>b.onclick=()=>$(b.dataset.uploadFor).click());$("heroFile").onchange=e=>uploadFile(e.target.files?.[0],"heroImage","homepage","heroPreview");$("btFile").onchange=e=>uploadFile(e.target.files?.[0],"btImage","homepage","btPreview");$("smartFile").onchange=e=>uploadFile(e.target.files?.[0],"smartBg","homepage","smartPreview");
document.querySelectorAll(".editortoolbar [data-cmd]").forEach(b=>b.onclick=()=>{document.execCommand(b.dataset.cmd,false,b.dataset.value||null);$("postContent").focus();dirty=true});$("linkBtn").onclick=()=>{const u=prompt("Enter URL");if(u){document.execCommand("createLink",false,u);dirty=true}};
$("exportData").onclick=()=>{const blob=new Blob([JSON.stringify({settings,homepage,blogPage,posts},null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`grouptravelairlines-content-${Date.now()}.json`;a.click();URL.revokeObjectURL(a.href)};

window.addEventListener("beforeunload",e=>{if(dirty){e.preventDefault();e.returnValue="";}});

supabase.auth.onAuthStateChange(async(_event,session)=>{if(!session){user=null;$("app").classList.add("hidden");$("loginView").classList.remove("hidden");return;}user=session.user;try{const {data:admin,error}=await supabase.from("admin_profiles").select("user_id,role,display_name").eq("user_id",user.id).maybeSingle();if(error)throw error;if(!admin||admin.role!=="admin"){await supabase.auth.signOut();msg("loginMessage","This account is not authorized as a Group Travel Airlines administrator.");return;}$("loginView").classList.add("hidden");$("app").classList.remove("hidden");$("currentUser").textContent=user.email||admin.display_name||"Admin";await loadSite();await loadPosts();}catch(e){await supabase.auth.signOut();msg("loginMessage",e.message||"Could not load admin data.");}});
